### ISSUE TITLE
dom repalce

### ISSUE THREAD

**Issue by will-citi** [dlrandy/note-issues#61]
$(element).find('img.emoji.final-render').each(i => {
        $(this).replaceWith($(document.createTextNode(originalMessage.text)));
    })

**Comment by dlrandy** [comment]
while(element.find('img.emoji.final-render').length > 0){
         let $img = element.find('img.emoji.final-render');
         $img.replaceWith($img.attr('title'));
     }

**Comment by dlrandy** [comment]
var $a = $('a'),
     $$a = $($a)的区别是？

**Comment by dlrandy** [comment]
context 有不同
